name: e2e-test-android

jobs:
  build_android_for_e2e:
    type: build
    params:
      platform: android
      profile: maestro # your eas build profile for E2E test

  maestro_test:
    needs: [build_android_for_e2e]
    type: maestro
    params:
      build_id: ${{ needs.build_android_for_e2e.outputs.build_id }}
      flow_path: ["maestro/auth.yml", "maestro/edit-profile.yml"]
